### ISSUE TITLE
Issues with "cpus" and "disks" on VM Guest

### ISSUE THREAD

**Issue by ccoenen** [novaquark/sysinfo_influxdb#24]
On one of the machines i'm testing right now, i get the following output for each subsystem. I am not sure if this is related to this being a VM, but it's my best bet at the moment.

    root@vm:/opt/sysinfo_influxdb# ./sysinfo_influxdb -c="cpu"
    
    #0: vm.cpu
    | id    | user  | nice  | sys   | idle  | wait  | total |
    | cpu   | 0     | 0     | 0     | 100   | 0     | 100   |
    
    
    
    
    root@vm:/opt/sysinfo_influxdb# ./sysinfo_influxdb -c="cpus"
    panic: runtime error: slice bounds out of range
    
    goroutine 20 [running]:
    runtime.panic(0x6ba5c0, 0x88624f)
            /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
    github.com/cloudfoundry/gosigar.func·004(0x0, 0x0, 0xf96)
            /gopath/src/github.com/cloudfoundry/gosigar/sigar_linux.go:119 +0x1b7
    github.com/cloudfoundry/gosigar.readFile(0xc208000380, 0xa, 0x7fe585f8ed50, 0x0, 0x0)
            /gopath/src/github.com/cloudfoundry/gosigar/sigar_linux.go:357 +0x245
    github.com/cloudfoundry/gosigar.(*CpuList).Get(0x7fe585f8eec8, 0x0, 0x0)
            /gopath/src/github.com/cloudfoundry/gosigar/sigar_linux.go:125 +0xe9
    main.cpus(0xc20800e580, 0x16, 0xc208004240, 0x0, 0x0)
            /gopath/src/github.com/novaquark/sysinfo_influxdb/main.go:359 +0x1b0
    created by main.main
            /gopath/src/github.com/novaquark/sysinfo_influxdb/main.go:187 +0xa02
    
    goroutine 16 [chan receive]:
    main.main()
            /gopath/src/github.com/novaquark/sysinfo_influxdb/main.go:191 +0xa7f
    
    goroutine 19 [finalizer wait]:
    runtime.park(0x41f270, 0x88a290, 0x8884e9)
            /usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
    runtime.parkunlock(0x88a290, 0x8884e9)
            /usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
    runfinq()
            /usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
    runtime.goexit()
            /usr/local/go/src/pkg/runtime/proc.c:1445
    
    
    
    
    root@vm:/opt/sysinfo_influxdb# ./sysinfo_influxdb -c="mem"
    
    #0: vm.mem
    | free  | used  | actualfree    | actualused    | total |
    | 3650183168    | 644784128     | 3877539840    | 417427456     | 4294967296    |
    
    
    
    
    root@vm:/opt/sysinfo_influxdb# ./sysinfo_influxdb -c="swap"
    
    #0: vm.swap
    | free  | used  | total |
    | 3159216128    | 62009344      | 3221225472    |
    
    
    
    
    root@vm:/opt/sysinfo_influxdb# ./sysinfo_influxdb -c="uptime"
    
    #0: vm.uptime
    | length        |
    | 1.438084e+06  |
    
    
    
    
    root@vm:/opt/sysinfo_influxdb# ./sysinfo_influxdb -c="load"
    
    #0: vm.load
    | one   | five  | fifteen       |
    | 0.03  | 0.01  | 0     |
    
    
    
    
    root@vm:/opt/sysinfo_influxdb# ./sysinfo_influxdb -c="network"
    
    #0: vm.network
    | iface | recv_bytes    | recv_packets  | recv_errs     | recv_drop     | recv_fifo     | recv_frame    | recv_compressed     | recv_multicast | trans_bytes   | trans_packets | trans_errs    | trans_drop    | trans_fifo    | trans_colls   | trans_carrier| trans_compressed      |
    | lo    | 15266 | 3     | 0     | 0     | 0     | 0     | 0     | 0     | 15266 | 3     | 0     | 0     | 0     | 0     | 0   | 0      |
    | venet0        | 704   | 9     | 0     | 0     | 0     | 0     | 0     | 0     | 754   | 10    | 0     | 0     | 0     | 0   | 0      | 0     |
    
    
    
    
    root@vm:/opt/sysinfo_influxdb# ./sysinfo_influxdb -c="disks"
    fatal error: all goroutines are asleep - deadlock!
    
    goroutine 16 [chan receive]:
    main.main()
            /gopath/src/github.com/novaquark/sysinfo_influxdb/main.go:191 +0xa7f
    
    goroutine 19 [finalizer wait]:
    runtime.park(0x41f270, 0x88a290, 0x8884e9)
            /usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
    runtime.parkunlock(0x88a290, 0x8884e9)
            /usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
    runfinq()
            /usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
    runtime.goexit()
            /usr/local/go/src/pkg/runtime/proc.c:1445

**Comment by nemunaire** [comment]
Hi @ccoenen,

I just fixed, in `develop` branch for now, the deadlock issue for the disks, but I imagine that happens because an error occurs. Can you build the `develop` branch, try to execute `./sysinfo_influxdb -c=disks` gain and report me the new error.

The error occurring for the CPUs function is in gosigar code. I'll report this error, but before, can you paste the content of the following command, executed in your VM:

    cat -e /proc/stat; wc /proc/stat

Thank you in advance.

**Comment by ccoenen** [comment]
the second request is simpler, so i answered that first:

    # cat -e /proc/stat; wc /proc/stat
    cpu  2181567 0 410886 150502608 123947 0 0 0$
    cpu0 2181567 0 410886 150502608 123947 0 0 0$
    intr 0$
    swap 0 0$
    $
    ctxt 264417282$
    btime 1418942026$
    processes 215136$
    procs_running 1$
    procs_blocked 0$
    10 33 188 /proc/stat

compiling from dev will take me a little longer, I have a debian with go 1.0.2 (without gzip.Writer), i'll have to set up a newer go, first.

**Comment by nemunaire** [comment]
Thanks!

I've compiled a version here:
https://github.com/novaquark/sysinfo_influxdb/releases/tag/0.5.3

This is a special release, with a wip fix for the CPU. Can you try it and let me know if the CPU is now correctly displayed.

And paste the error for disks.

**Comment by nemunaire** [comment]
Pull request made for fixing CPU upstream : https://github.com/cloudfoundry/gosigar/pull/20

I don't understand why there is this curious problem with `disks`, can you run and paste the result of the following command:

    tail /proc/diskstats; wc /proc/diskstats

**Comment by ccoenen** [comment]
uh... this is odd? But on the other hand, it probably explains why it's failing :D 

    root@vm:/# tail /proc/diskstats; wc /proc/diskstats
    tail: cannot open `/proc/diskstats' for reading: No such file or directory
    wc: /proc/diskstats: No such file or directory

**Comment by nemunaire** [comment]
Ok, I checked the code: errors in collect functions are never handled, and the main loop continue while there is no data.

Are you on a VPS (running by something like OpenVZ)? I think this is the only case where `/proc/diskstats` doesn't exist. In such situations, disks are shared between VMs, so information given by this file can leak information about others VMs' disk usage. I don't think we can get those information in this case.

**Comment by ccoenen** [comment]
Yup, this seems to be openvz.

    root@vm:/# virt-what
    openvz
